[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "next"
  command = "next dev"
  port = 8888
  targetPort = 3000
  autoLaunch = true

# Netlify automatically handles function proxying
