[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[dev]
  framework = "next"
  command = "next dev"
  port = 8888
  targetPort = 3000
  autoLaunch = true

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200