[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[dev]
  command = ""
  port = 8888
  targetPort = 3000
  autoLaunch = false

# Netlify automatically handles function proxying
