[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 